package com.huntkey.rx.sceo.common.service.common.model;

import java.util.Date;

public class EmailLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOG_SEND_EMAIL.mailId
     *
     * @mbg.generated Mon Jun 26 13:53:36 CST 2017
     */
    private String mailid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOG_SEND_EMAIL.mailModuleCode
     *
     * @mbg.generated Mon Jun 26 13:53:36 CST 2017
     */
    private String mailmodulecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOG_SEND_EMAIL.mailSubject
     *
     * @mbg.generated Mon Jun 26 13:53:36 CST 2017
     */
    private String mailsubject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOG_SEND_EMAIL.mailSendTime
     *
     * @mbg.generated Mon Jun 26 13:53:36 CST 2017
     */
    private Date mailsendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOG_SEND_EMAIL.mailSendStauts
     *
     * @mbg.generated Mon Jun 26 13:53:36 CST 2017
     */
    private String mailsendstauts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOG_SEND_EMAIL.mailErrorResponse
     *
     * @mbg.generated Mon Jun 26 13:53:36 CST 2017
     */
    private String mailerrorresponse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOG_SEND_EMAIL.addtime
     *
     * @mbg.generated Mon Jun 26 13:53:36 CST 2017
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOG_SEND_EMAIL.adduser
     *
     * @mbg.generated Mon Jun 26 13:53:36 CST 2017
     */
    private String adduser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOG_SEND_EMAIL.mailId
     *
     * @return the value of LOG_SEND_EMAIL.mailId
     *
     * @mbg.generated Mon Jun 26 13:53:36 CST 2017
     */
    public String getMailid() {
        return mailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOG_SEND_EMAIL.mailId
     *
     * @param mailid the value for LOG_SEND_EMAIL.mailId
     *
     * @mbg.generated Mon Jun 26 13:53:36 CST 2017
     */
    public void setMailid(String mailid) {
        this.mailid = mailid == null ? null : mailid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOG_SEND_EMAIL.mailModuleCode
     *
     * @return the value of LOG_SEND_EMAIL.mailModuleCode
     *
     * @mbg.generated Mon Jun 26 13:53:36 CST 2017
     */
    public String getMailmodulecode() {
        return mailmodulecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOG_SEND_EMAIL.mailModuleCode
     *
     * @param mailmodulecode the value for LOG_SEND_EMAIL.mailModuleCode
     *
     * @mbg.generated Mon Jun 26 13:53:36 CST 2017
     */
    public void setMailmodulecode(String mailmodulecode) {
        this.mailmodulecode = mailmodulecode == null ? null : mailmodulecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOG_SEND_EMAIL.mailSubject
     *
     * @return the value of LOG_SEND_EMAIL.mailSubject
     *
     * @mbg.generated Mon Jun 26 13:53:36 CST 2017
     */
    public String getMailsubject() {
        return mailsubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOG_SEND_EMAIL.mailSubject
     *
     * @param mailsubject the value for LOG_SEND_EMAIL.mailSubject
     *
     * @mbg.generated Mon Jun 26 13:53:36 CST 2017
     */
    public void setMailsubject(String mailsubject) {
        this.mailsubject = mailsubject == null ? null : mailsubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOG_SEND_EMAIL.mailSendTime
     *
     * @return the value of LOG_SEND_EMAIL.mailSendTime
     *
     * @mbg.generated Mon Jun 26 13:53:36 CST 2017
     */
    public Date getMailsendtime() {
        return mailsendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOG_SEND_EMAIL.mailSendTime
     *
     * @param mailsendtime the value for LOG_SEND_EMAIL.mailSendTime
     *
     * @mbg.generated Mon Jun 26 13:53:36 CST 2017
     */
    public void setMailsendtime(Date mailsendtime) {
        this.mailsendtime = mailsendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOG_SEND_EMAIL.mailSendStauts
     *
     * @return the value of LOG_SEND_EMAIL.mailSendStauts
     *
     * @mbg.generated Mon Jun 26 13:53:36 CST 2017
     */
    public String getMailsendstauts() {
        return mailsendstauts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOG_SEND_EMAIL.mailSendStauts
     *
     * @param mailsendstauts the value for LOG_SEND_EMAIL.mailSendStauts
     *
     * @mbg.generated Mon Jun 26 13:53:36 CST 2017
     */
    public void setMailsendstauts(String mailsendstauts) {
        this.mailsendstauts = mailsendstauts == null ? null : mailsendstauts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOG_SEND_EMAIL.mailErrorResponse
     *
     * @return the value of LOG_SEND_EMAIL.mailErrorResponse
     *
     * @mbg.generated Mon Jun 26 13:53:36 CST 2017
     */
    public String getMailerrorresponse() {
        return mailerrorresponse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOG_SEND_EMAIL.mailErrorResponse
     *
     * @param mailerrorresponse the value for LOG_SEND_EMAIL.mailErrorResponse
     *
     * @mbg.generated Mon Jun 26 13:53:36 CST 2017
     */
    public void setMailerrorresponse(String mailerrorresponse) {
        this.mailerrorresponse = mailerrorresponse == null ? null : mailerrorresponse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOG_SEND_EMAIL.addtime
     *
     * @return the value of LOG_SEND_EMAIL.addtime
     *
     * @mbg.generated Mon Jun 26 13:53:36 CST 2017
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOG_SEND_EMAIL.addtime
     *
     * @param addtime the value for LOG_SEND_EMAIL.addtime
     *
     * @mbg.generated Mon Jun 26 13:53:36 CST 2017
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOG_SEND_EMAIL.adduser
     *
     * @return the value of LOG_SEND_EMAIL.adduser
     *
     * @mbg.generated Mon Jun 26 13:53:36 CST 2017
     */
    public String getAdduser() {
        return adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOG_SEND_EMAIL.adduser
     *
     * @param adduser the value for LOG_SEND_EMAIL.adduser
     *
     * @mbg.generated Mon Jun 26 13:53:36 CST 2017
     */
    public void setAdduser(String adduser) {
        this.adduser = adduser == null ? null : adduser.trim();
    }
}