package com.huntkey.rx.sceo.common.service.common.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SmsLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table LOG_SEND_MESSAGE
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table LOG_SEND_MESSAGE
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table LOG_SEND_MESSAGE
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOG_SEND_MESSAGE
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    public SmsLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOG_SEND_MESSAGE
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOG_SEND_MESSAGE
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOG_SEND_MESSAGE
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOG_SEND_MESSAGE
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOG_SEND_MESSAGE
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOG_SEND_MESSAGE
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOG_SEND_MESSAGE
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOG_SEND_MESSAGE
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOG_SEND_MESSAGE
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOG_SEND_MESSAGE
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LOG_SEND_MESSAGE
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSmlgidIsNull() {
            addCriterion("smlgId is null");
            return (Criteria) this;
        }

        public Criteria andSmlgidIsNotNull() {
            addCriterion("smlgId is not null");
            return (Criteria) this;
        }

        public Criteria andSmlgidEqualTo(String value) {
            addCriterion("smlgId =", value, "smlgid");
            return (Criteria) this;
        }

        public Criteria andSmlgidNotEqualTo(String value) {
            addCriterion("smlgId <>", value, "smlgid");
            return (Criteria) this;
        }

        public Criteria andSmlgidGreaterThan(String value) {
            addCriterion("smlgId >", value, "smlgid");
            return (Criteria) this;
        }

        public Criteria andSmlgidGreaterThanOrEqualTo(String value) {
            addCriterion("smlgId >=", value, "smlgid");
            return (Criteria) this;
        }

        public Criteria andSmlgidLessThan(String value) {
            addCriterion("smlgId <", value, "smlgid");
            return (Criteria) this;
        }

        public Criteria andSmlgidLessThanOrEqualTo(String value) {
            addCriterion("smlgId <=", value, "smlgid");
            return (Criteria) this;
        }

        public Criteria andSmlgidLike(String value) {
            addCriterion("smlgId like", value, "smlgid");
            return (Criteria) this;
        }

        public Criteria andSmlgidNotLike(String value) {
            addCriterion("smlgId not like", value, "smlgid");
            return (Criteria) this;
        }

        public Criteria andSmlgidIn(List<String> values) {
            addCriterion("smlgId in", values, "smlgid");
            return (Criteria) this;
        }

        public Criteria andSmlgidNotIn(List<String> values) {
            addCriterion("smlgId not in", values, "smlgid");
            return (Criteria) this;
        }

        public Criteria andSmlgidBetween(String value1, String value2) {
            addCriterion("smlgId between", value1, value2, "smlgid");
            return (Criteria) this;
        }

        public Criteria andSmlgidNotBetween(String value1, String value2) {
            addCriterion("smlgId not between", value1, value2, "smlgid");
            return (Criteria) this;
        }

        public Criteria andSmlgmodulecodeIsNull() {
            addCriterion("smlgModuleCode is null");
            return (Criteria) this;
        }

        public Criteria andSmlgmodulecodeIsNotNull() {
            addCriterion("smlgModuleCode is not null");
            return (Criteria) this;
        }

        public Criteria andSmlgmodulecodeEqualTo(String value) {
            addCriterion("smlgModuleCode =", value, "smlgmodulecode");
            return (Criteria) this;
        }

        public Criteria andSmlgmodulecodeNotEqualTo(String value) {
            addCriterion("smlgModuleCode <>", value, "smlgmodulecode");
            return (Criteria) this;
        }

        public Criteria andSmlgmodulecodeGreaterThan(String value) {
            addCriterion("smlgModuleCode >", value, "smlgmodulecode");
            return (Criteria) this;
        }

        public Criteria andSmlgmodulecodeGreaterThanOrEqualTo(String value) {
            addCriterion("smlgModuleCode >=", value, "smlgmodulecode");
            return (Criteria) this;
        }

        public Criteria andSmlgmodulecodeLessThan(String value) {
            addCriterion("smlgModuleCode <", value, "smlgmodulecode");
            return (Criteria) this;
        }

        public Criteria andSmlgmodulecodeLessThanOrEqualTo(String value) {
            addCriterion("smlgModuleCode <=", value, "smlgmodulecode");
            return (Criteria) this;
        }

        public Criteria andSmlgmodulecodeLike(String value) {
            addCriterion("smlgModuleCode like", value, "smlgmodulecode");
            return (Criteria) this;
        }

        public Criteria andSmlgmodulecodeNotLike(String value) {
            addCriterion("smlgModuleCode not like", value, "smlgmodulecode");
            return (Criteria) this;
        }

        public Criteria andSmlgmodulecodeIn(List<String> values) {
            addCriterion("smlgModuleCode in", values, "smlgmodulecode");
            return (Criteria) this;
        }

        public Criteria andSmlgmodulecodeNotIn(List<String> values) {
            addCriterion("smlgModuleCode not in", values, "smlgmodulecode");
            return (Criteria) this;
        }

        public Criteria andSmlgmodulecodeBetween(String value1, String value2) {
            addCriterion("smlgModuleCode between", value1, value2, "smlgmodulecode");
            return (Criteria) this;
        }

        public Criteria andSmlgmodulecodeNotBetween(String value1, String value2) {
            addCriterion("smlgModuleCode not between", value1, value2, "smlgmodulecode");
            return (Criteria) this;
        }

        public Criteria andSmlgphoneIsNull() {
            addCriterion("smlgPhone is null");
            return (Criteria) this;
        }

        public Criteria andSmlgphoneIsNotNull() {
            addCriterion("smlgPhone is not null");
            return (Criteria) this;
        }

        public Criteria andSmlgphoneEqualTo(String value) {
            addCriterion("smlgPhone =", value, "smlgphone");
            return (Criteria) this;
        }

        public Criteria andSmlgphoneNotEqualTo(String value) {
            addCriterion("smlgPhone <>", value, "smlgphone");
            return (Criteria) this;
        }

        public Criteria andSmlgphoneGreaterThan(String value) {
            addCriterion("smlgPhone >", value, "smlgphone");
            return (Criteria) this;
        }

        public Criteria andSmlgphoneGreaterThanOrEqualTo(String value) {
            addCriterion("smlgPhone >=", value, "smlgphone");
            return (Criteria) this;
        }

        public Criteria andSmlgphoneLessThan(String value) {
            addCriterion("smlgPhone <", value, "smlgphone");
            return (Criteria) this;
        }

        public Criteria andSmlgphoneLessThanOrEqualTo(String value) {
            addCriterion("smlgPhone <=", value, "smlgphone");
            return (Criteria) this;
        }

        public Criteria andSmlgphoneLike(String value) {
            addCriterion("smlgPhone like", value, "smlgphone");
            return (Criteria) this;
        }

        public Criteria andSmlgphoneNotLike(String value) {
            addCriterion("smlgPhone not like", value, "smlgphone");
            return (Criteria) this;
        }

        public Criteria andSmlgphoneIn(List<String> values) {
            addCriterion("smlgPhone in", values, "smlgphone");
            return (Criteria) this;
        }

        public Criteria andSmlgphoneNotIn(List<String> values) {
            addCriterion("smlgPhone not in", values, "smlgphone");
            return (Criteria) this;
        }

        public Criteria andSmlgphoneBetween(String value1, String value2) {
            addCriterion("smlgPhone between", value1, value2, "smlgphone");
            return (Criteria) this;
        }

        public Criteria andSmlgphoneNotBetween(String value1, String value2) {
            addCriterion("smlgPhone not between", value1, value2, "smlgphone");
            return (Criteria) this;
        }

        public Criteria andSmlgcontentIsNull() {
            addCriterion("smlgContent is null");
            return (Criteria) this;
        }

        public Criteria andSmlgcontentIsNotNull() {
            addCriterion("smlgContent is not null");
            return (Criteria) this;
        }

        public Criteria andSmlgcontentEqualTo(String value) {
            addCriterion("smlgContent =", value, "smlgcontent");
            return (Criteria) this;
        }

        public Criteria andSmlgcontentNotEqualTo(String value) {
            addCriterion("smlgContent <>", value, "smlgcontent");
            return (Criteria) this;
        }

        public Criteria andSmlgcontentGreaterThan(String value) {
            addCriterion("smlgContent >", value, "smlgcontent");
            return (Criteria) this;
        }

        public Criteria andSmlgcontentGreaterThanOrEqualTo(String value) {
            addCriterion("smlgContent >=", value, "smlgcontent");
            return (Criteria) this;
        }

        public Criteria andSmlgcontentLessThan(String value) {
            addCriterion("smlgContent <", value, "smlgcontent");
            return (Criteria) this;
        }

        public Criteria andSmlgcontentLessThanOrEqualTo(String value) {
            addCriterion("smlgContent <=", value, "smlgcontent");
            return (Criteria) this;
        }

        public Criteria andSmlgcontentLike(String value) {
            addCriterion("smlgContent like", value, "smlgcontent");
            return (Criteria) this;
        }

        public Criteria andSmlgcontentNotLike(String value) {
            addCriterion("smlgContent not like", value, "smlgcontent");
            return (Criteria) this;
        }

        public Criteria andSmlgcontentIn(List<String> values) {
            addCriterion("smlgContent in", values, "smlgcontent");
            return (Criteria) this;
        }

        public Criteria andSmlgcontentNotIn(List<String> values) {
            addCriterion("smlgContent not in", values, "smlgcontent");
            return (Criteria) this;
        }

        public Criteria andSmlgcontentBetween(String value1, String value2) {
            addCriterion("smlgContent between", value1, value2, "smlgcontent");
            return (Criteria) this;
        }

        public Criteria andSmlgcontentNotBetween(String value1, String value2) {
            addCriterion("smlgContent not between", value1, value2, "smlgcontent");
            return (Criteria) this;
        }

        public Criteria andSmlgsendtimeIsNull() {
            addCriterion("smlgSendTime is null");
            return (Criteria) this;
        }

        public Criteria andSmlgsendtimeIsNotNull() {
            addCriterion("smlgSendTime is not null");
            return (Criteria) this;
        }

        public Criteria andSmlgsendtimeEqualTo(Date value) {
            addCriterion("smlgSendTime =", value, "smlgsendtime");
            return (Criteria) this;
        }

        public Criteria andSmlgsendtimeNotEqualTo(Date value) {
            addCriterion("smlgSendTime <>", value, "smlgsendtime");
            return (Criteria) this;
        }

        public Criteria andSmlgsendtimeGreaterThan(Date value) {
            addCriterion("smlgSendTime >", value, "smlgsendtime");
            return (Criteria) this;
        }

        public Criteria andSmlgsendtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("smlgSendTime >=", value, "smlgsendtime");
            return (Criteria) this;
        }

        public Criteria andSmlgsendtimeLessThan(Date value) {
            addCriterion("smlgSendTime <", value, "smlgsendtime");
            return (Criteria) this;
        }

        public Criteria andSmlgsendtimeLessThanOrEqualTo(Date value) {
            addCriterion("smlgSendTime <=", value, "smlgsendtime");
            return (Criteria) this;
        }

        public Criteria andSmlgsendtimeIn(List<Date> values) {
            addCriterion("smlgSendTime in", values, "smlgsendtime");
            return (Criteria) this;
        }

        public Criteria andSmlgsendtimeNotIn(List<Date> values) {
            addCriterion("smlgSendTime not in", values, "smlgsendtime");
            return (Criteria) this;
        }

        public Criteria andSmlgsendtimeBetween(Date value1, Date value2) {
            addCriterion("smlgSendTime between", value1, value2, "smlgsendtime");
            return (Criteria) this;
        }

        public Criteria andSmlgsendtimeNotBetween(Date value1, Date value2) {
            addCriterion("smlgSendTime not between", value1, value2, "smlgsendtime");
            return (Criteria) this;
        }

        public Criteria andSmlgresstatusIsNull() {
            addCriterion("smlgResStatus is null");
            return (Criteria) this;
        }

        public Criteria andSmlgresstatusIsNotNull() {
            addCriterion("smlgResStatus is not null");
            return (Criteria) this;
        }

        public Criteria andSmlgresstatusEqualTo(String value) {
            addCriterion("smlgResStatus =", value, "smlgresstatus");
            return (Criteria) this;
        }

        public Criteria andSmlgresstatusNotEqualTo(String value) {
            addCriterion("smlgResStatus <>", value, "smlgresstatus");
            return (Criteria) this;
        }

        public Criteria andSmlgresstatusGreaterThan(String value) {
            addCriterion("smlgResStatus >", value, "smlgresstatus");
            return (Criteria) this;
        }

        public Criteria andSmlgresstatusGreaterThanOrEqualTo(String value) {
            addCriterion("smlgResStatus >=", value, "smlgresstatus");
            return (Criteria) this;
        }

        public Criteria andSmlgresstatusLessThan(String value) {
            addCriterion("smlgResStatus <", value, "smlgresstatus");
            return (Criteria) this;
        }

        public Criteria andSmlgresstatusLessThanOrEqualTo(String value) {
            addCriterion("smlgResStatus <=", value, "smlgresstatus");
            return (Criteria) this;
        }

        public Criteria andSmlgresstatusLike(String value) {
            addCriterion("smlgResStatus like", value, "smlgresstatus");
            return (Criteria) this;
        }

        public Criteria andSmlgresstatusNotLike(String value) {
            addCriterion("smlgResStatus not like", value, "smlgresstatus");
            return (Criteria) this;
        }

        public Criteria andSmlgresstatusIn(List<String> values) {
            addCriterion("smlgResStatus in", values, "smlgresstatus");
            return (Criteria) this;
        }

        public Criteria andSmlgresstatusNotIn(List<String> values) {
            addCriterion("smlgResStatus not in", values, "smlgresstatus");
            return (Criteria) this;
        }

        public Criteria andSmlgresstatusBetween(String value1, String value2) {
            addCriterion("smlgResStatus between", value1, value2, "smlgresstatus");
            return (Criteria) this;
        }

        public Criteria andSmlgresstatusNotBetween(String value1, String value2) {
            addCriterion("smlgResStatus not between", value1, value2, "smlgresstatus");
            return (Criteria) this;
        }

        public Criteria andSmlgresstatustextIsNull() {
            addCriterion("smlgResStatusText is null");
            return (Criteria) this;
        }

        public Criteria andSmlgresstatustextIsNotNull() {
            addCriterion("smlgResStatusText is not null");
            return (Criteria) this;
        }

        public Criteria andSmlgresstatustextEqualTo(String value) {
            addCriterion("smlgResStatusText =", value, "smlgresstatustext");
            return (Criteria) this;
        }

        public Criteria andSmlgresstatustextNotEqualTo(String value) {
            addCriterion("smlgResStatusText <>", value, "smlgresstatustext");
            return (Criteria) this;
        }

        public Criteria andSmlgresstatustextGreaterThan(String value) {
            addCriterion("smlgResStatusText >", value, "smlgresstatustext");
            return (Criteria) this;
        }

        public Criteria andSmlgresstatustextGreaterThanOrEqualTo(String value) {
            addCriterion("smlgResStatusText >=", value, "smlgresstatustext");
            return (Criteria) this;
        }

        public Criteria andSmlgresstatustextLessThan(String value) {
            addCriterion("smlgResStatusText <", value, "smlgresstatustext");
            return (Criteria) this;
        }

        public Criteria andSmlgresstatustextLessThanOrEqualTo(String value) {
            addCriterion("smlgResStatusText <=", value, "smlgresstatustext");
            return (Criteria) this;
        }

        public Criteria andSmlgresstatustextLike(String value) {
            addCriterion("smlgResStatusText like", value, "smlgresstatustext");
            return (Criteria) this;
        }

        public Criteria andSmlgresstatustextNotLike(String value) {
            addCriterion("smlgResStatusText not like", value, "smlgresstatustext");
            return (Criteria) this;
        }

        public Criteria andSmlgresstatustextIn(List<String> values) {
            addCriterion("smlgResStatusText in", values, "smlgresstatustext");
            return (Criteria) this;
        }

        public Criteria andSmlgresstatustextNotIn(List<String> values) {
            addCriterion("smlgResStatusText not in", values, "smlgresstatustext");
            return (Criteria) this;
        }

        public Criteria andSmlgresstatustextBetween(String value1, String value2) {
            addCriterion("smlgResStatusText between", value1, value2, "smlgresstatustext");
            return (Criteria) this;
        }

        public Criteria andSmlgresstatustextNotBetween(String value1, String value2) {
            addCriterion("smlgResStatusText not between", value1, value2, "smlgresstatustext");
            return (Criteria) this;
        }

        public Criteria andAddtimeIsNull() {
            addCriterion("addtime is null");
            return (Criteria) this;
        }

        public Criteria andAddtimeIsNotNull() {
            addCriterion("addtime is not null");
            return (Criteria) this;
        }

        public Criteria andAddtimeEqualTo(Date value) {
            addCriterion("addtime =", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeNotEqualTo(Date value) {
            addCriterion("addtime <>", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeGreaterThan(Date value) {
            addCriterion("addtime >", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("addtime >=", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeLessThan(Date value) {
            addCriterion("addtime <", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeLessThanOrEqualTo(Date value) {
            addCriterion("addtime <=", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeIn(List<Date> values) {
            addCriterion("addtime in", values, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeNotIn(List<Date> values) {
            addCriterion("addtime not in", values, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeBetween(Date value1, Date value2) {
            addCriterion("addtime between", value1, value2, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeNotBetween(Date value1, Date value2) {
            addCriterion("addtime not between", value1, value2, "addtime");
            return (Criteria) this;
        }

        public Criteria andAdduserIsNull() {
            addCriterion("adduser is null");
            return (Criteria) this;
        }

        public Criteria andAdduserIsNotNull() {
            addCriterion("adduser is not null");
            return (Criteria) this;
        }

        public Criteria andAdduserEqualTo(String value) {
            addCriterion("adduser =", value, "adduser");
            return (Criteria) this;
        }

        public Criteria andAdduserNotEqualTo(String value) {
            addCriterion("adduser <>", value, "adduser");
            return (Criteria) this;
        }

        public Criteria andAdduserGreaterThan(String value) {
            addCriterion("adduser >", value, "adduser");
            return (Criteria) this;
        }

        public Criteria andAdduserGreaterThanOrEqualTo(String value) {
            addCriterion("adduser >=", value, "adduser");
            return (Criteria) this;
        }

        public Criteria andAdduserLessThan(String value) {
            addCriterion("adduser <", value, "adduser");
            return (Criteria) this;
        }

        public Criteria andAdduserLessThanOrEqualTo(String value) {
            addCriterion("adduser <=", value, "adduser");
            return (Criteria) this;
        }

        public Criteria andAdduserLike(String value) {
            addCriterion("adduser like", value, "adduser");
            return (Criteria) this;
        }

        public Criteria andAdduserNotLike(String value) {
            addCriterion("adduser not like", value, "adduser");
            return (Criteria) this;
        }

        public Criteria andAdduserIn(List<String> values) {
            addCriterion("adduser in", values, "adduser");
            return (Criteria) this;
        }

        public Criteria andAdduserNotIn(List<String> values) {
            addCriterion("adduser not in", values, "adduser");
            return (Criteria) this;
        }

        public Criteria andAdduserBetween(String value1, String value2) {
            addCriterion("adduser between", value1, value2, "adduser");
            return (Criteria) this;
        }

        public Criteria andAdduserNotBetween(String value1, String value2) {
            addCriterion("adduser not between", value1, value2, "adduser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LOG_SEND_MESSAGE
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 27 13:55:36 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LOG_SEND_MESSAGE
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}