package com.huntkey.rx.sceo.common.service.common.model;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

import com.huntkey.rx.commons.utils.rest.Result;
import com.huntkey.rx.sceo.common.service.common.model.to.SimpleSmsTO;

public class SmsLog {
	
	public SmsLog(SimpleSmsTO to) {
		// TODO Auto-generated constructor stub
		SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
		this.smlgmodulecode=to.getSmlgModuleCode();
		this.smlgphone=to.getSmlgPhone();
		this.smlgcontent=to.getSmlgContent();
		try {
			this.smlgsendtime=(to.getSmlgSendTime()==null || to.getSmlgSendTime().length()<1)?
					Calendar.getInstance().getTime():sdf.parse(to.getSmlgSendTime());
			this.addtime=Calendar.getInstance().getTime();		
		} catch (ParseException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		this.adduser=to.getAddUser();
	}
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOG_SEND_MESSAGE.smlgId
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    private String smlgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOG_SEND_MESSAGE.smlgModuleCode
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    private String smlgmodulecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOG_SEND_MESSAGE.smlgPhone
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    private String smlgphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOG_SEND_MESSAGE.smlgContent
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    private String smlgcontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOG_SEND_MESSAGE.smlgSendTime
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    private Date smlgsendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOG_SEND_MESSAGE.smlgResStatus
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    private String smlgresstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOG_SEND_MESSAGE.smlgResStatusText
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    private String smlgresstatustext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOG_SEND_MESSAGE.addtime
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOG_SEND_MESSAGE.adduser
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    private String adduser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOG_SEND_MESSAGE.smlgId
     *
     * @return the value of LOG_SEND_MESSAGE.smlgId
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    public String getSmlgid() {
        return smlgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOG_SEND_MESSAGE.smlgId
     *
     * @param smlgid the value for LOG_SEND_MESSAGE.smlgId
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    public void setSmlgid(String smlgid) {
        this.smlgid = smlgid == null ? null : smlgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOG_SEND_MESSAGE.smlgModuleCode
     *
     * @return the value of LOG_SEND_MESSAGE.smlgModuleCode
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    public String getSmlgmodulecode() {
        return smlgmodulecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOG_SEND_MESSAGE.smlgModuleCode
     *
     * @param smlgmodulecode the value for LOG_SEND_MESSAGE.smlgModuleCode
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    public void setSmlgmodulecode(String smlgmodulecode) {
        this.smlgmodulecode = smlgmodulecode == null ? null : smlgmodulecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOG_SEND_MESSAGE.smlgPhone
     *
     * @return the value of LOG_SEND_MESSAGE.smlgPhone
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    public String getSmlgphone() {
        return smlgphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOG_SEND_MESSAGE.smlgPhone
     *
     * @param smlgphone the value for LOG_SEND_MESSAGE.smlgPhone
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    public void setSmlgphone(String smlgphone) {
        this.smlgphone = smlgphone == null ? null : smlgphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOG_SEND_MESSAGE.smlgContent
     *
     * @return the value of LOG_SEND_MESSAGE.smlgContent
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    public String getSmlgcontent() {
        return smlgcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOG_SEND_MESSAGE.smlgContent
     *
     * @param smlgcontent the value for LOG_SEND_MESSAGE.smlgContent
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    public void setSmlgcontent(String smlgcontent) {
        this.smlgcontent = smlgcontent == null ? null : smlgcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOG_SEND_MESSAGE.smlgSendTime
     *
     * @return the value of LOG_SEND_MESSAGE.smlgSendTime
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    public Date getSmlgsendtime() {
        return smlgsendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOG_SEND_MESSAGE.smlgSendTime
     *
     * @param smlgsendtime the value for LOG_SEND_MESSAGE.smlgSendTime
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    public void setSmlgsendtime(Date smlgsendtime) {
        this.smlgsendtime = smlgsendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOG_SEND_MESSAGE.smlgResStatus
     *
     * @return the value of LOG_SEND_MESSAGE.smlgResStatus
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    public String getSmlgresstatus() {
        return smlgresstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOG_SEND_MESSAGE.smlgResStatus
     *
     * @param smlgresstatus the value for LOG_SEND_MESSAGE.smlgResStatus
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    public void setSmlgresstatus(String smlgresstatus) {
        this.smlgresstatus = smlgresstatus == null ? null : smlgresstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOG_SEND_MESSAGE.smlgResStatusText
     *
     * @return the value of LOG_SEND_MESSAGE.smlgResStatusText
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    public String getSmlgresstatustext() {
        return smlgresstatustext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOG_SEND_MESSAGE.smlgResStatusText
     *
     * @param smlgresstatustext the value for LOG_SEND_MESSAGE.smlgResStatusText
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    public void setSmlgresstatustext(String smlgresstatustext) {
        this.smlgresstatustext = smlgresstatustext == null ? null : smlgresstatustext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOG_SEND_MESSAGE.addtime
     *
     * @return the value of LOG_SEND_MESSAGE.addtime
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOG_SEND_MESSAGE.addtime
     *
     * @param addtime the value for LOG_SEND_MESSAGE.addtime
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOG_SEND_MESSAGE.adduser
     *
     * @return the value of LOG_SEND_MESSAGE.adduser
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    public String getAdduser() {
        return adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOG_SEND_MESSAGE.adduser
     *
     * @param adduser the value for LOG_SEND_MESSAGE.adduser
     *
     * @mbg.generated Tue Jun 27 13:55:36 CST 2017
     */
    public void setAdduser(String adduser) {
        this.adduser = adduser == null ? null : adduser.trim();
    }
}