set define off
spool 11_检定管理相关表变更.log

--增加检定信息表字段
alter table T_DEVICE_CERTIFICATION add(EQUIPMENT_TYPE varchar2(10));
alter table T_DEVICE_CERTIFICATION add(EQUIPMENT_NBR varchar2(32));
alter table T_DEVICE_CERTIFICATION add(UPDATE_TIME DATE);
alter table T_DEVICE_CERTIFICATION add(ORG_NAME varchar2(256));

COMMENT ON COLUMN T_DEVICE_CERTIFICATION.EQUIPMENT_TYPE IS '设备类型';
COMMENT ON COLUMN T_DEVICE_CERTIFICATION.EQUIPMENT_NBR IS '设备编号/出厂编号';
COMMENT ON COLUMN T_DEVICE_CERTIFICATION.ORG_NAME IS '管理机构 批量导入时使用';


/*==============================================================*/
/* Table: T_DEVICE_CERTIFICATION_RECORD                         */
/*==============================================================*/
CREATE TABLE T_DEVICE_CERTIFICATION_RECORD 
(
   RECORD_ID            VARCHAR2(32)         NOT NULL,
   IMPORT_DATE          VARCHAR2(20)         NOT NULL,
   EQUIPMENT_NBR        VARCHAR2(32),
   CERTIFICATION_NBR    VARCHAR2(32),
   EQUIPMENT_TYPE       VARCHAR2(10),
   ORG_NAME             VARCHAR2(256),
   DEVICE_NAME          VARCHAR2(256),
   MODEL_NAME           VARCHAR2(256),
   CERTIFICATED_DATE    DATE,
   EXPIRE_DATE          DATE,
   EXPIRE_MARK          VARCHAR2(1),
   CERTIFICATED_RESULT  VARCHAR2(10),
   CERTIFICATED_ORG     VARCHAR2(256),
   CERTIFICATED_PERSON  VARCHAR2(40),
   IMPORT_MARK          VARCHAR2(10),
   CREATE_TIME          DATE,
   CREATE_PERSON        VARCHAR2(40),
   UPDATE_TIME          DATE,
   UPDATE_PERSON        VARCHAR2(40),
   IMPORT_ACCEPT        VARCHAR2(32),
   CONSTRAINT PK_CERTIFICATION_RECORD PRIMARY KEY (RECORD_ID)
);

COMMENT ON TABLE T_DEVICE_CERTIFICATION_RECORD IS
'系统检定证书批量导入记录表';

COMMENT ON COLUMN T_DEVICE_CERTIFICATION_RECORD.IMPORT_DATE IS
'导入批次';

COMMENT ON COLUMN T_DEVICE_CERTIFICATION_RECORD.CERTIFICATION_NBR IS
'证书编号';

COMMENT ON COLUMN T_DEVICE_CERTIFICATION_RECORD."EQUIPMENT_TYPE" IS
'设备类型名称 导入时根据器具名称进行转换 目前只有六种 :固定测速;区间测速;电警;酒检;卡口; 车载.';

COMMENT ON COLUMN T_DEVICE_CERTIFICATION_RECORD.ORG_NAME IS
'委托单位';

COMMENT ON COLUMN T_DEVICE_CERTIFICATION_RECORD.DEVICE_NAME IS
'器具名称';

COMMENT ON COLUMN T_DEVICE_CERTIFICATION_RECORD.MODEL_NAME IS
'设备型号 存名称';

COMMENT ON COLUMN T_DEVICE_CERTIFICATION_RECORD.CERTIFICATED_DATE IS
'检定日期';

COMMENT ON COLUMN T_DEVICE_CERTIFICATION_RECORD.EXPIRE_DATE IS
'有效日期 两个月内到期或超期前台提醒';

COMMENT ON COLUMN T_DEVICE_CERTIFICATION_RECORD.EXPIRE_MARK IS
'检定状态  1.正常 2:两个月后超期 3:1个月后超期 4:超期';

COMMENT ON COLUMN T_DEVICE_CERTIFICATION_RECORD.CERTIFICATED_RESULT IS
'检定结果 1 合格，2 不合格';

COMMENT ON COLUMN T_DEVICE_CERTIFICATION_RECORD.CERTIFICATED_ORG IS
'检定机构 存名称';

COMMENT ON COLUMN T_DEVICE_CERTIFICATION_RECORD.CERTIFICATED_PERSON IS
'检定人';

COMMENT ON COLUMN T_DEVICE_CERTIFICATION_RECORD.IMPORT_MARK IS
'导入标记  1:导入成功; 2:非交警设备;3:未登记;4:其他原因';

COMMENT ON COLUMN T_DEVICE_CERTIFICATION_RECORD.CREATE_TIME IS
'添加时间';

COMMENT ON COLUMN T_DEVICE_CERTIFICATION_RECORD.CREATE_PERSON IS
'添加人';

COMMENT ON COLUMN T_DEVICE_CERTIFICATION_RECORD.UPDATE_TIME IS
'修改时间';

COMMENT ON COLUMN T_DEVICE_CERTIFICATION_RECORD.UPDATE_PERSON IS
'修改人';

COMMENT ON COLUMN T_DEVICE_CERTIFICATION_RECORD.IMPORT_ACCEPT IS
'同一次操作流水相同，用于批量更新检定证书信息表';


spool off

exit;